### ISSUE TITLE
Missing text_encoder_chollet_float_16.tflite

### ISSUE THREAD

**Issue by hannesa2** [farmaker47/Diffusion_models_app#1]
On branch `colab_with_ngrok_api` I run into
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/3314607/219000236-f9c1c043-9f3a-41f7-a978-2b75baa15d25.png">

From where should this `text_encoder_chollet_float_16.tflite` come from ?

**Comment by farmaker47** [comment]
Hi @hannesa2 
The link is there at the README file. Is it broken?

**Comment by hannesa2** [comment]
Ahh, a small, but important detail 😉
Thank you for the repo
